run:
  timeout: 5m
  tests: true
  skip-dirs:
    - gen
    - vendor
linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
issues:
  exclude-files:
    - ".*\\.pb\\.go"
    - "gen/.*"
